name: sarsys_app_server
description: SARSys App Server consumed by SarSys apps
version: 0.0.1
author: Kenneth Gulbrands√∏y <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  jaguar_jwt: ^2.1.6
  event_source:
    path: ../event_source
  sarsys_domain:
    path: ../sarsys_domain
  sarsys_http_core:
    path: ../sarsys_http_core


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  build_runner: ^1.7.0

dependency_overrides:
  jose:
#    path: ../../jose
    git:
      url: https://github.com/DISCOOS/jose.git
      ref: issue/10_only_throw_when_x509_only
