name: event_source
description: A client library for event sourcing using eventstore streams
version: 0.1.0
author: DISCO Open Source <support@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  uuid: ^2.0.2
  equatable: ^1.0.1
  json_patch: ^2.0.0
  json_schema: ^2.2.1
  validators: ^2.0.0+1
  json_annotation: ^2.0.0
  hive: ^1.4.1+1
  stack_trace: ^1.9.6

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.0
  json_serializable: ^2.0.0
